services:
  intranet:
    build:
      context: ./
      dockerfile: intranet/Dockerfile
    image: intranet
    container_name: intranet
    networks:
      - sp-network
  portal:
    build:
      context: ./
      dockerfile: portal/Dockerfile
    image: portal
    container_name: portal
    networks:
      - sp-network
  proxy:
    build:
      context: ./
      dockerfile: proxy/Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "8080:80"
    depends_on:
      - intranet
      - portal
    networks:
      - sp-network
  dns:
    build: ./dns
    image: dns
    container_name: dns
    restart: always
    tty: true
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/primary:/etc/bind
    networks:
      - sp-network  
  email:
    build: ./email
    image: email
    container_name: email
    ports:
      - "25:25/tcp"
      - "100:100/tcp"
      - "143:143/tcp"
      - "587:587/tcp"
      - "993:993/tcp"
      - "995:995/tcp"
    networks:
      - sp-network
  webmail:
      build:
        context: ./webmail
      image: webmail
      container_name: webmail
      restart: always
      tty: true
      volumes:
        - ./webmail/rainloop:/var/www/html/rainloop
      depends_on:
        - email
      networks:
        - sp-network

#Docker Networks
networks:
  sp-network:
    driver: bridge